### ISSUE TITLE
如何比较不同文件夹的同名图片

### ISSUE THREAD

**Issue by Ir1d** [MegEngine/MegSpot#15]
我拖入了两个文件夹，分别是 000-010.jpg 然后各自全选，发现比较的是 000 & 001，求问如何比较 a/000 & b/000; a/001 & b/001 呢

**Comment by hjwforever** [comment]
> - MegSpot有默认的排序算法，但支持用户自定义文件排序的配置文件`.MegSpotSort.ini`
> - MegSpot可以通过**手动按顺序的添加方式**或[文件长廊](https://github.com/MegEngine/MegSpot/wiki/%E6%96%87%E4%BB%B6%E9%95%BF%E5%BB%8Al)来随时调整文件列表排序(实时生效)

为了使对比文件列表按照预期顺序排列，这里针对三种情景给出目前的几种解决方式：
- 生成文件时(自动): 
  - 方式一：若通过算法等程序处理生成不同系列的图片，可以按照**一定的命名顺序**来**自动生成**图像并放在**同一文件夹**中, 如1-1、1-2，2-1、2-2；（依赖MegSpot**默认的排序算法**）
  - 方式二：生成不同系列图像在**同一文件夹**时，编写脚本程序**自动生成**排序配置文件`.MegSpotSort.ini`（也可**手动更改**），每行一个文件名，则文件会按该排序顺序显示排列。（**自定义排序顺序**，优先级高于MegSpot默认排序算法）
- 添加文件时(手动)：按照你想要的顺序对图像进行**手动添加**，如在不同目录时，先添加a/1.jpg，再添加b/1.jpg
- 添加文件后(手动):  打开[文件长廊](https://github.com/MegEngine/MegSpot/wiki/%E6%96%87%E4%BB%B6%E9%95%BF%E5%BB%8Al)，通过**手动拖拽**文件来随时调整文件列表排序(实时生效)

**Comment by hjwforever** [comment]
- 方式一(手动更改文件排序配置文件)

https://user-images.githubusercontent.com/58247686/177907647-4380169f-2ba0-471f-bb8d-fee7afd39c65.mp4

- 方式二(按顺序手动添加)、方式三([文件长廊](https://github.com/MegEngine/MegSpot/wiki/%E6%96%87%E4%BB%B6%E9%95%BF%E5%BB%8A)手动拖拽调整排序)

https://user-images.githubusercontent.com/58247686/177906975-44d1468d-3336-4d57-b295-b77bb8d29ed1.mp4

**Comment by Ir1d** [comment]
感谢，想问下有计划添加这样一种比较模式的功能吗

**Comment by hjwforever** [comment]
后续应该会将**不同目录下同名文件一键排序**(文件名相同，路径不同)的功能加入到**文件长廊**

**Comment by hjwforever** [comment]
新版本v1.4.0已支持~
