### ISSUE TITLE
[feature request] need show pixel location of choosed pixel

### ISSUE THREAD

**Issue by huhumeng2** [MegEngine/MegSpot#16]
hi, i just try your nice tool, but it not provides the pixel coordinate together with the pixel color info, i want use this feature to now where is my point
just like the style in OpenCV. 
![image](https://user-images.githubusercontent.com/67313891/184346047-0230b477-f51a-4b87-8eb0-6aa06c37754e.png)

**Comment by hjwforever** [comment]
yes, we will support the feature as it's in our roadmap.

**Comment by hjwforever** [comment]
#17
