### ISSUE TITLE
是否可以支持重叠比较？

### ISSUE THREAD

**Issue by makejiang** [MegEngine/MegSpot#19]
就是两幅图重叠在一起，然后用一根移动线（垂直或水平）来比较原图和修改图，这样可以直观对比图中某个物品在两图中的差异

**Comment by hjwforever** [comment]
是的，我们具有这个功能[拖拽对比](https://github.com/MegEngine/MegSpot/wiki/%E6%8B%96%E6%8B%BD%E5%AF%B9%E6%AF%94)。

你可以在图片对比文件选择界面，通过点击“拖拽对比”进入。
![image](https://user-images.githubusercontent.com/58247686/190939884-a62873c2-0e92-415d-91ef-3462dc79c68c.png)

**Comment by makejiang** [comment]
找到了，非常感谢！
