### ISSUE TITLE
Support per video frame step

### ISSUE THREAD

**Issue by tkkcc** [MegEngine/MegSpot#21]
Per video frame step is useful to align unsyned video. Currently the only way is to adjust timestamp number  manually, it's pain. 

BTW, [video-compare](https://github.com/pixop/video-compare/blob/cc35c7e26d91ae5b0328dafea411ad6b94aba64a/README.md?plain=1#L83-L84) support this.

**Comment by hjwforever** [comment]
supports video compare， and we had optimized the function.[](https://github.com/MegEngine/MegSpot/releases/tag/v2.0.6)

**Comment by hjwforever** [comment]
Video comparison is now supported and optimized. [download](https://github.com/MegEngine/MegSpot/releases/tag/v2.0.6)
