### ISSUE TITLE
导入多张图快照,界面只能显示两张图.

### ISSUE THREAD

**Issue by WadeChenn** [MegEngine/MegSpot#29]
导入多张图快照,界面只能显示两张图.

**Comment by hjwforever** [comment]
> 导入多张图快照,界面只能显示两张图.

哈喽，请问使用的MegSpot版本是多少？我这里测试四张图生成快照，然后加载快照，是可以正常加载显示的

**Comment by WadeChenn** [comment]
> 

您好 感谢回答..是4*1的模式,2*2是正常的

**Comment by hjwforever** [comment]
> > 
> 
> 您好 感谢回答..是4_1的模式,2_2是正常的

好的，我们会尽快修复~

**Comment by hjwforever** [comment]
已修复，等待下次发版。
