### ISSUE TITLE
MegSpot doesn't launch

### ISSUE THREAD

**Issue by PENGUINLIONG** [MegEngine/MegSpot#3]
I downloaded  `MegSpot-1.1.1.exe` from [the release page](https://github.com/MegEngine/MegSpot/releases). For the first time I launch the app there is no window popping up, but if I start the program again it gives me feedback like this:

![图片](https://user-images.githubusercontent.com/1487605/140438626-118e7ffd-8051-4ac7-b4f2-6d57cd7c042f.png)

**Comment by PENGUINLIONG** [comment]
Also the released binary is unsigned which pushes windows to paranoid. It's probably better to sign your releases.

![图片](https://user-images.githubusercontent.com/1487605/140438952-d1034602-bbb8-4356-a0b4-2b280bac7cc3.png)

**Comment by weiweiwei256** [comment]
第一个问题 应该没有影响功能吧  感觉像是启动了两次
windows下 现在已经计划申请下证书了  进行中

**Comment by PENGUINLIONG** [comment]
There is no UI showing up tho, while the process is running. The application is completely unusable in this case. FYI, this machine is running Windows 10 21H1 19043.1237, on Ryzen 7 5800X.

**Comment by PENGUINLIONG** [comment]
I just realized it's an antimalware service killed the process because the software is unsigned. By group policy of my company the service cannot be terminated so I still see it as an issue. The problem ought to be fixed once the application's got a certificate.

**Comment by weiweiwei256** [comment]
v1.2.1 add code certificate. Please check again.
