### ISSUE TITLE
[Bug] 某些分辨率的图像不能正确同步地缩放

### ISSUE THREAD

**Issue by tglsf** [MegEngine/MegSpot#31]
MegSpot v2.2.2
Windows 10 x64 22H2
显示器分辨率：2560x1440 缩放：125%

复现：
1. 创建一个分辨率为900x900的图像，以及一个分辨率为1425x1425的图像。
2. 转到比较功能。尝试反复放大和缩小图像、调整窗口大小。
3. 问题发生。右上角的 "自适应 "按钮不能正常工作。有时图像会闪烁片刻，然后立即变为错误的尺寸。

**Comment by aruoxi** [comment]
> MegSpot v2.2.2 Windows 10 x64 22H2 显示器分辨率：2560x1440 缩放：125%
> 
> 复现：
> 
> 1. 创建一个分辨率为900x900的图像，以及一个分辨率为1425x1425的图像。
> 2. 转到比较功能。尝试反复放大和缩小图像、调整窗口大小。
> 3. 问题发生。右上角的 "自适应 "按钮不能正常工作。有时图像会闪烁片刻，然后立即变为错误的尺寸。

感谢反馈，我们会尽快修复，随着下次发版修复上线~
