### ISSUE TITLE
Chrome download warns dangerous on Windows10 for .exe

### ISSUE THREAD

**Issue by zchrissirhcz** [MegEngine/MegSpot#4]
系统： Windows10

浏览器版本：Chrome 已是最新版本
版本 95.0.4638.69（正式版本） （64 位）

下载链接：
https://github.com/MegEngine/MegSpot/releases/download/v1.1.1/MegSpot-1.1.1.exe

![image](https://user-images.githubusercontent.com/3831847/140442082-efca42f7-8237-4c9f-8ead-41c971f66090.png)

![image](https://user-images.githubusercontent.com/3831847/140441986-ca429e45-15d2-425c-a0d2-400a799b0f1b.png)

![image](https://user-images.githubusercontent.com/3831847/140441967-53c06009-a85f-4b83-bbe8-f0aefedc4b1d.png)

预期结果： 希望Chrome不报警告。

**Comment by weiweiwei256** [comment]
这个是由于缺少证书所致   由于之前测试没有证书也可以自动更新 所以就没有后续申请  我会近期申请一下  之后就不要出问题了

**Comment by weiweiwei256** [comment]
v1.2.1 fiexed.
