### ISSUE TITLE
文件夹数量太多导致卡

### ISSUE THREAD

**Issue by laborer123** [MegEngine/MegSpot#40]
一个文件夹一千多张，两个两千多，选择所有时候卡住，一张图片10-20MB左右

**Comment by HLImg** [comment]
是的，这种情况下无法正常compare

**Comment by hjwforever** [comment]
感谢反馈！周末修一波

修复文件长廊image gallery资源占用问题
- [ ] 图像列表使用懒加载

**Comment by Zerospeaker** [comment]
请问这个功能加上了吗，现在打开图片数量上千的文件夹还是会卡住

**Comment by hjwforever** [comment]
> 请问这个功能加上了吗，现在打开图片数量上千的文件夹还是会卡住

抱歉没有及时修复这个问题，目前新版已经修复。
新版对文件长廊image galler的图像列表启用了懒加载、异步解码。

可以测试一下是否还卡顿

**Comment by Zerospeaker** [comment]
> > 请问这个功能加上了吗，现在打开图片数量上千的文件夹还是会卡住
> 
> 抱歉没有及时修复这个问题，目前新版已经修复。 新版对文件长廊image galler的图像列表启用了懒加载、异步解码。
> 
> 可以测试一下是否还卡顿

试了下2.2.11还是会卡住，有时界面直接全白。我选择对比两个图像文件夹，每个文件夹包含5000多张图片，可能太大了。能不能只在对比相应的某两张图片时才加载对应的图片。

**Comment by hjwforever** [comment]
> > > 请问这个功能加上了吗，现在打开图片数量上千的文件夹还是会卡住
> > 
> > 抱歉没有及时修复这个问题，目前新版已经修复。 新版对文件长廊image galler的图像列表启用了懒加载、异步解码。
> > 
> > 可以测试一下是否还卡顿
> 
> 试了下2.2.11还是会卡住，有时界面直接全白。我选择对比两个图像文件夹，每个文件夹包含5000多张图片，可能太大了。能不能只在对比相应的某两张图片时才加载对应的图片。

我更新后只测试了普通的图像对比。
现在普通的图像对比中，应该就是只加载对比显示的两张图片。只有打开文件长廊是才会懒加载图像列表。(旧版是会加载所有的图像)

请问你使用的是图像序列对比的功能吗？windows还是其他系统？

**Comment by Zerospeaker** [comment]
> > > > 请问这个功能加上了吗，现在打开图片数量上千的文件夹还是会卡住
> > > 
> > > 
> > > 抱歉没有及时修复这个问题，目前新版已经修复。 新版对文件长廊image galler的图像列表启用了懒加载、异步解码。
> > > 可以测试一下是否还卡顿
> > 
> > 
> > 试了下2.2.11还是会卡住，有时界面直接全白。我选择对比两个图像文件夹，每个文件夹包含5000多张图片，可能太大了。能不能只在对比相应的某两张图片时才加载对应的图片。
> 
> 我更新后只测试了普通的图像对比。 现在普通的图像对比中，应该就是只加载对比显示的两张图片。只有打开文件长廊是才会懒加载图像列表。(旧版是一上来就会加载所有的图像)
> 
> 请问你使用的是图像序列对比的功能吗？windows还是其他系统？

MegSpot 2.2.11，系统配置为MacBook Pro，2.6 GHz 六核Intel Core i7 ，16 GB 2667 MHz DDR4。
打开两个文件夹，每个文件夹包含5700张图片，每个文件夹总大小为10GB。连续添加这两个文件夹后无问题，但点击任意一个添加的文件夹，并在图片列表中选中一张图片后，软件卡死。

**Comment by Zerospeaker** [comment]
> 可以试试这个测试版，使用了原生image元素加载图像，加载会快一点[v2.2.21](https://github.com/MegEngine/MegSpot/releases/tag/v2.2.21)
试了下这个版本v2.2.21，情况并没有得到改善，在添加第二个文件夹后软件全白。
且文件列表详细信息无法显示，只能选择缩略图显示。
<img width="1365" alt="image" src="https://github.com/user-attachments/assets/898402cd-ae9d-419c-9c4d-8b6c757ed9c6">
<img width="1363" alt="image" src="https://github.com/user-attachments/assets/6bfa02a0-8f38-4eb2-b94a-9eb490f7f05a">

**Comment by hjwforever** [comment]
> > 可以试试这个测试版，使用了原生image元素加载图像，加载会快一点[v2.2.21](https://github.com/MegEngine/MegSpot/releases/tag/v2.2.21)
> > 试了下这个版本v2.2.21，情况并没有得到改善，在添加第二个文件夹后软件全白。
> > 且文件列表详细信息无法显示，只能选择缩略图显示。
> 
> <img alt="image" width="1365" src="https://private-user-images.githubusercontent.com/57103141/381027446-898402cd-ae9d-419c-9c4d-8b6c757ed9c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODg0MDYsIm5iZiI6MTczMDE4ODEwNiwicGF0aCI6Ii81NzEwMzE0MS8zODEwMjc0NDYtODk4NDAyY2QtYWU5ZC00MTljLTljNGQtOGI2Yzc1N2VkOWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4YTBjODUxZGM3NjM3MDliNDM4YzdjNTJkNzllMDhkYTdiMTc4Y2MyMDg2ZmMxODk0YjIzMWJiM2UzMDMzMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.B6sJSTthpkttzNOs-Kxbq4h0G9Ux9BLcuprigpWnYH4"> <img alt="image" width="1363" src="https://private-user-images.githubusercontent.com/57103141/381027735-6bfa02a0-8f38-4eb2-b94a-9eb490f7f05a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxODg0MDYsIm5iZiI6MTczMDE4ODEwNiwicGF0aCI6Ii81NzEwMzE0MS8zODEwMjc3MzUtNmJmYTAyYTAtOGYzOC00ZWIyLWI5NGEtOWViNDkwZjdmMDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA3NDgyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI4Zjg1NmU5MjFlZDE3NjVkNmRiNjYyNzBmZTJiZjdhODk5YjBkMmQ4Y2M5ZjM3Mjc3NmNhMTZmNjhkMmY5MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.KxTHTF7B4ubX70AGeNKSv0JBfBBJUYHu-3PC9B-gYhk">

这个grid列表确实没有添加懒加载，我是在ctrl+F呼出的文件长廊添加了懒加载。
![image](https://github.com/user-attachments/assets/94cef82f-4f09-4a0b-9c9a-f4735c9a6239)

那等我再更新下这个grid视图的列表，添加下懒加载。

在此之前，你可以使用普通的图像对比，应该会好很多。

**Comment by hjwforever** [comment]
> > 可以试试这个测试版，使用了原生image元素加载图像，加载会快一点[v2.2.21](https://github.com/MegEngine/MegSpot/releases/tag/v2.2.21)
> > 试了下这个版本v2.2.21，情况并没有得到改善，在添加第二个文件夹后软件全白。
> > 且文件列表详细信息无法显示，只能选择缩略图显示。
> 
> <img alt="image" width="1365" src="https://private-user-images.githubusercontent.com/57103141/381027446-898402cd-ae9d-419c-9c4d-8b6c757ed9c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTc1ODgsIm5iZiI6MTczMDIxNzI4OCwicGF0aCI6Ii81NzEwMzE0MS8zODEwMjc0NDYtODk4NDAyY2QtYWU5ZC00MTljLTljNGQtOGI2Yzc1N2VkOWM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE1NTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlMzFjN2MxMWUyZWIzOWZiNjIyZDAxYTA2ZDExZTQxMTM3MTI3ZTUyYWVlMGQwMGQwNGI3ZWFkMzVmY2NkY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mKmP3oNPaqjaD_Ox5WBZF4fOrcTkQ98ADq2pxWB6_oY"> <img alt="image" width="1363" src="https://private-user-images.githubusercontent.com/57103141/381027735-6bfa02a0-8f38-4eb2-b94a-9eb490f7f05a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAyMTc1ODgsIm5iZiI6MTczMDIxNzI4OCwicGF0aCI6Ii81NzEwMzE0MS8zODEwMjc3MzUtNmJmYTAyYTAtOGYzOC00ZWIyLWI5NGEtOWViNDkwZjdmMDVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDE1NTQ0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyOTBkZTQ1MTZkNjEwZjg1NTUyYjc3YjJjODhkM2E3NTQ2ODExOWMxODJjZDhlMzFhYmM0ZTM1YTVjMzI5ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.osf3Cr5wisKEoTknya34mm9L8v9aOwP5rZ6LCnKfhFA">

已更新，图像预览列表也使用了懒加载。下载新版即可[v2.2.12](https://github.com/MegEngine/MegSpot/releases/tag/v2.2.12)

**Comment by jwhx** [comment]
@Zerospeaker 已更新，图像预览列表也使用了懒加载。下载新版即可[v2.2.12](https://github.com/MegEngine/MegSpot/releases/tag/v2.2.12)

**Comment by Zerospeaker** [comment]
> @Zerospeaker 已更新，图像预览列表也使用了懒加载。下载新版即可[v2.2.12](https://github.com/MegEngine/MegSpot/releases/tag/v2.2.12)

感谢支持，测试下了确实可以用了。不过还有两个小问题，如果能解决会更好：
1. 在用于图像序列对比时，对超大数量文件夹的文件列表点击`全部选择`还是会卡住，不过只选择几十张图片已经没有卡顿问题了。
<img width="589" alt="image" src="https://github.com/user-attachments/assets/678fd1c6-6c57-44df-949a-b102210fff3f">
2. 导入两个文件夹，每个文件夹还是5700张图片，在分别选择几十张图片（我这里是67）作为两个图片序列后，点击对比图像序列并选择这两个图片序列后，软件会全白。
<img width="1469" alt="image" src="https://github.com/user-attachments/assets/8d6b803f-6622-433d-8a9c-7e19d3ee6704">
<img width="1790" alt="image" src="https://github.com/user-attachments/assets/66d61ea4-0a42-40c1-89f7-710ab30d0355">
需要reload才会出现正常对比界面
<img width="391" alt="image" src="https://github.com/user-attachments/assets/54f6070b-8815-47e9-9a6d-dab1f1449a14">
<img width="1788" alt="image" src="https://github.com/user-attachments/assets/47c33c6e-016b-48ad-b1a6-67ef80ab0035">
同时，在进入对比界面后，返回文件选择界面还是会全白。
<img width="1791" alt="image" src="https://github.com/user-attachments/assets/3184a03c-2767-4a1f-90b2-7aaa10ab0ff1">
只能再reload一下，点击进入主界面，从主界面才能进入文件选择界面。
<img width="502" alt="image" src="https://github.com/user-attachments/assets/e28d23d5-de07-4b69-8626-7d3ef819d1c1">

**Comment by jwhx** [comment]
> > @Zerospeaker 已更新，图像预览列表也使用了懒加载。下载新版即可[v2.2.12](https://github.com/MegEngine/MegSpot/releases/tag/v2.2.12)
> 
> 感谢支持，测试下了确实可以用了。不过还有两个小问题，如果能解决会更好：
> 1. 在用于图像序列对比时，对超大数量文件夹的文件列表点击`全部选择`还是会卡住，不过只选择几十张图片已经没有卡顿问题了。
> <img width="589" alt="image" src="https://github.com/user-attachments/assets/678fd1c6-6c57-44df-949a-b102210fff3f">
> 2. 导入两个文件夹，每个文件夹还是5700张图片，在分别选择几十张图片（我这里是67）作为两个图片序列后，点击对比图像序列并选择这两个图片序列后，软件会全白。
> <img width="1469" alt="image" src="https://github.com/user-attachments/assets/8d6b803f-6622-433d-8a9c-7e19d3ee6704">
> <img width="1790" alt="image" src="https://github.com/user-attachments/assets/66d61ea4-0a42-40c1-89f7-710ab30d0355">
> 需要reload才会出现正常对比界面
> <img width="391" alt="image" src="https://github.com/user-attachments/assets/54f6070b-8815-47e9-9a6d-dab1f1449a14">
> <img width="1788" alt="image" src="https://github.com/user-attachments/assets/47c33c6e-016b-48ad-b1a6-67ef80ab0035">
> 同时，在进入对比界面后，返回文件选择界面还是会全白。
> <img width="1791" alt="image" src="https://github.com/user-attachments/assets/3184a03c-2767-4a1f-90b2-7aaa10ab0ff1">
> 只能再reload一下，点击进入主界面，从主界面才能进入文件选择界面。
> <img width="502" alt="image" src="https://github.com/user-attachments/assets/e28d23d5-de07-4b69-8626-7d3ef819d1c1">
> 

感谢反馈，我看下怎么优化解决
