### ISSUE TITLE
没有硬解吗

### ISSUE THREAD

**Issue by king23333cao** [MegEngine/MegSpot#44]
如标题：
GPU一点都没占上，看起来这已经导致了些许播放卡顿。

还有，只支持MP4格式吗？已知".ts"格式不支持

**Comment by hjwforever** [comment]
- [x] 支持视频硬解
    卡顿问题可能是 #40 等已知bug引起的，或者可能你在`同时播放多个高清视频`
- [ ] 暂未支持`hls`视频协议，需要后续加入`hls.js`或其他工具库进行支持

在我这测试是支持视频硬解的
1. windows直接播放普通视频，`GPU`的`Video Decode`使用率**低**
    ![image](https://github.com/user-attachments/assets/59b57761-7c4b-48b8-a756-8dd137241d79)
2. windows直接播放hevc视频，`GPU`的`Video Decode`使用率**高**
    ![image](https://github.com/user-attachments/assets/d909177a-4c0d-4384-a51a-1eda11c3bb04)
3. MegSpot播放hevc视频，`GPU`的`Video Decode`使用率**高**
    ![image](https://github.com/user-attachments/assets/737bdf04-5025-4f14-9d5a-dde4636a5030)

**Comment by hjwforever** [comment]
1. 请问你在对比几个视频，视频格式和分辨率如何？
2. 文件列表中是否已经存在了许多文件？

如果以上两种因素都不太会影响到视频播放卡顿，那可能是目前的`播放策略`导致的卡顿

**Comment by hjwforever** [comment]
另外在MegSpot调试控制台，通过API查询也显示MegSpot是已启用硬解功能的：
![image](https://github.com/user-attachments/assets/6d45fb24-411b-4109-9b2b-f0874b34a0d0)
