### ISSUE TITLE
安装完最新版本的v2.2.12，打开软件出现问题

### ISSUE THREAD

**Issue by Wzh10032** [MegEngine/MegSpot#45]
![image](https://github.com/user-attachments/assets/81be5ce2-bd75-4b79-950e-0bf2202f283f)
![image](https://github.com/user-attachments/assets/1066db35-b014-44ff-934c-1bc5ebfd6a51)

会一直卡在这个加载资源的地方，软件界面为空白

**Comment by jwhx** [comment]
> ![image](https://private-user-images.githubusercontent.com/78578726/385787761-81be5ce2-bd75-4b79-950e-0bf2202f283f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTMwOTgsIm5iZiI6MTczMTU1Mjc5OCwicGF0aCI6Ii83ODU3ODcyNi8zODU3ODc3NjEtODFiZTVjZTItYmQ3NS00Yjc5LTk1MGUtMGJmMjIwMmYyODNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAyNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzQ3YjMzZGJkNmZmODIzNzJhZTg0NmY1NGEwOTNiMzI3N2YwYTc2MzI3ODVlNWMyMTFmMzQ2MDUxZjc4ZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qQkzkO-1k0QHMetbxWLxoTZewVNVHnbIN9QLdpuCeZM) ![image](https://private-user-images.githubusercontent.com/78578726/385788123-1066db35-b014-44ff-934c-1bc5ebfd6a51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1NTMwOTgsIm5iZiI6MTczMTU1Mjc5OCwicGF0aCI6Ii83ODU3ODcyNi8zODU3ODgxMjMtMTA2NmRiMzUtYjAxNC00NGZmLTkzNGMtMWJjNWViZmQ2YTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE0VDAyNTMxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0ZjI3YWUyYzhhOTBmNjVlMjc0YmVmODM4MDIxZWZiYjA2ZjRmNzJkMDlkODk5OGM3MTBiNzg3NTIyNWM3ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._dtoMSrVG-8ORH5In6O_6UzJ_-u5TRD9JL9Mz_iuy68)
> 
> 会一直卡在这个加载资源的地方，软件界面为空白

你好，请问下你的系统平台，windows或者ubuntu的话，我可以快速进行下复现

**Comment by Wzh10032** [comment]
使用的是Windows 11 专业版，版本号23H2

**Comment by jwhx** [comment]
> 使用的是Windows 11 专业版，版本号23H2

我使用win11专业版 卸载重新安装了`正式版v2.2.12`，能正常使用。系统版本如下：

> Edition	Windows 11 Pro
Version	23H2
Installed on	‎11/‎19/‎2023
OS build	22631.4037
Experience	Windows Feature Experience Pack 1000.22700.1027.0

**Comment by jwhx** [comment]
> 使用的是Windows 11 专业版，版本号23H2

- 先卸载重新安装试试
- 能检查下是否下错了版本吗，如果安装的是`预览版v2.2.21`，这个预览版有问题，可能无法使用。
- 都不行的话，可以看下控制台是否有报错日志
    >  1. 点击打开开发者工具，等待几秒后弹出 
    ![image](https://github.com/user-attachments/assets/16c4af7b-5ea9-41d4-853c-e8f9a0ca8f24)
    > 2. 点击console, 重点截图红色报错处
      ![image](https://github.com/user-attachments/assets/fcfd33ef-07fe-4680-aba3-9fe2a247da28)

**Comment by Wzh10032** [comment]
您好，我之前没有详细描述清楚我遇到的问题，可能给您造成了困扰。我上个月安装的这个软件，版本是[v2.2.10]，当时打开很多图像的文件夹时会卡顿，就没有继续使用。然后我在昨天发现[v2.2.12]版本解决了这个问题，于是卸载的原先的[v2.2.10]版本，安装了[v2.2.12]版本，但是打开就遇到了上面这个情况。

![image](https://github.com/user-attachments/assets/0688621b-da45-4636-84fa-9bfb12156681)
![image](https://github.com/user-attachments/assets/9a842f58-9bfe-4029-97bf-6674eb14d77b)
这边是没有红色的报错，都是警告信息

**Comment by Wzh10032** [comment]
> > 使用的是Windows 11 专业版，版本号23H2
> 
> * 先卸载重新安装试试
> * 能检查下是否下错了版本吗，如果安装的是`预览版v2.2.21`，这个预览版有问题，可能无法使用。
> * 都不行的话，可以看下控制台是否有报错日志
>   > 1. 点击打开开发者工具，等待几秒后弹出
>   >    ![image](https://private-user-images.githubusercontent.com/58247686/386595685-16c4af7b-5ea9-41d4-853c-e8f9a0ca8f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzUyMDUsIm5iZiI6MTczMTY3NDkwNSwicGF0aCI6Ii81ODI0NzY4Ni8zODY1OTU2ODUtMTZjNGFmN2ItNWVhOS00MWQ0LTg1M2MtZThmOWEwY2E4ZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEyNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOWEwOGU3ZWMxYWE2OTViMmViYzA1ZTc1M2FlM2ViZjAzZGNjMDFjYzFlOTEwZmM2ZDdmYTkzYzc0NzAxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YMgEVTdeVCOF4oi31OA6BKpGRcDivZbWnlkuR-j7S_8)
>   > 2. 点击console, 重点截图红色报错处
>   >    ![image](https://private-user-images.githubusercontent.com/58247686/386595653-fcfd33ef-07fe-4680-aba3-9fe2a247da28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzUyMDUsIm5iZiI6MTczMTY3NDkwNSwicGF0aCI6Ii81ODI0NzY4Ni8zODY1OTU2NTMtZmNmZDMzZWYtMDdmZS00NjgwLWFiYTMtOWZlMmEyNDdkYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEyNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OTdkNzFhZGY4NWI3NWQwZDllZjJkNTgzZDJhYTI1YTk1MjM5ODMzYjM2NmI3NDA1NjVmNTlhYjJkYTA1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v5n3C4QerXIHPLREDYtDZE-TAIL7lIkW83TLfDPENxA)

我尝试了重新安装，还是会遇到同样的问题

**Comment by jwhx** [comment]
> > > 使用的是Windows 11 专业版，版本号23H2
> > 
> > 
> > 
> > * 先卸载重新安装试试
> > * 能检查下是否下错了版本吗，如果安装的是`预览版v2.2.21`，这个预览版有问题，可能无法使用。
> > * 都不行的话，可以看下控制台是否有报错日志
> >   > 1. 点击打开开发者工具，等待几秒后弹出
> >   >    ![image](https://private-user-images.githubusercontent.com/58247686/386595685-16c4af7b-5ea9-41d4-853c-e8f9a0ca8f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzUyMDUsIm5iZiI6MTczMTY3NDkwNSwicGF0aCI6Ii81ODI0NzY4Ni8zODY1OTU2ODUtMTZjNGFmN2ItNWVhOS00MWQ0LTg1M2MtZThmOWEwY2E4ZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEyNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOWEwOGU3ZWMxYWE2OTViMmViYzA1ZTc1M2FlM2ViZjAzZGNjMDFjYzFlOTEwZmM2ZDdmYTkzYzc0NzAxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YMgEVTdeVCOF4oi31OA6BKpGRcDivZbWnlkuR-j7S_8)
> >   > 2. 点击console, 重点截图红色报错处
> >   >    ![image](https://private-user-images.githubusercontent.com/58247686/386595653-fcfd33ef-07fe-4680-aba3-9fe2a247da28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzUyMDUsIm5iZiI6MTczMTY3NDkwNSwicGF0aCI6Ii81ODI0NzY4Ni8zODY1OTU2NTMtZmNmZDMzZWYtMDdmZS00NjgwLWFiYTMtOWZlMmEyNDdkYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEyNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OTdkNzFhZGY4NWI3NWQwZDllZjJkNTgzZDJhYTI1YTk1MjM5ODMzYjM2NmI3NDA1NjVmNTlhYjJkYTA1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v5n3C4QerXIHPLREDYtDZE-TAIL7lIkW83TLfDPENxA)
> 
> 我尝试了重新安装，还是会遇到同样的问题

可以试下手动清除缓存数据：
- 先退出MegSpot，然后删除 `C:\Users\<系统用户名>\AppData\Roaming\MegSpot`下的`vuex.json`文件，这个操作会删除直接添加的目录、文件列表信息。
- 再次打开MegSpot试试

**Comment by hjwforever** [comment]
可以添加q群等我们通知这个 在线版demo的体验时间
782365536

**Comment by Wzh10032** [comment]
> > > > 使用的是Windows 11 专业版，版本号23H2
> > > 
> > > 
> > > 
> > > * 先卸载重新安装试试
> > > * 能检查下是否下错了版本吗，如果安装的是`预览版v2.2.21`，这个预览版有问题，可能无法使用。
> > > * 都不行的话，可以看下控制台是否有报错日志
> > >   > 1. 点击打开开发者工具，等待几秒后弹出
> > >   >    ![image](https://private-user-images.githubusercontent.com/58247686/386595685-16c4af7b-5ea9-41d4-853c-e8f9a0ca8f24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzUyMDUsIm5iZiI6MTczMTY3NDkwNSwicGF0aCI6Ii81ODI0NzY4Ni8zODY1OTU2ODUtMTZjNGFmN2ItNWVhOS00MWQ0LTg1M2MtZThmOWEwY2E4ZjI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEyNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlOWEwOGU3ZWMxYWE2OTViMmViYzA1ZTc1M2FlM2ViZjAzZGNjMDFjYzFlOTEwZmM2ZDdmYTkzYzc0NzAxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YMgEVTdeVCOF4oi31OA6BKpGRcDivZbWnlkuR-j7S_8)
> > >   > 2. 点击console, 重点截图红色报错处
> > >   >    ![image](https://private-user-images.githubusercontent.com/58247686/386595653-fcfd33ef-07fe-4680-aba3-9fe2a247da28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NzUyMDUsIm5iZiI6MTczMTY3NDkwNSwicGF0aCI6Ii81ODI0NzY4Ni8zODY1OTU2NTMtZmNmZDMzZWYtMDdmZS00NjgwLWFiYTMtOWZlMmEyNDdkYTI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDEyNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OTdkNzFhZGY4NWI3NWQwZDllZjJkNTgzZDJhYTI1YTk1MjM5ODMzYjM2NmI3NDA1NjVmNTlhYjJkYTA1NzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v5n3C4QerXIHPLREDYtDZE-TAIL7lIkW83TLfDPENxA)
> > 
> > 
> > 我尝试了重新安装，还是会遇到同样的问题
> 
> 可以试下手动清除缓存数据：
> 
> * 先退出MegSpot，然后删除 `C:\Users\<系统用户名>\AppData\Roaming\MegSpot`下的`vuex.json`文件，这个操作会删除直接添加的目录、文件列表信息。
> * 再次打开MegSpot试试

非常感谢您的帮助，我在删除`vuex.json`文件后MegSpot就可以正常使用了👍🏼

**Comment by CherylXuli** [comment]
请问这个问题在Mac上面应该怎么解决呢？一直卡在准备资源的界面，重装软件也不行
