### ISSUE TITLE
Downladed .zip file broken

### ISSUE THREAD

**Issue by zchrissirhcz** [MegEngine/MegSpot#5]
Hi, I just downloaded the MegSpot-1.1.1.zip file from https://github.com/MegEngine/MegSpot/releases/download/v1.1.1/MegSpot-1.1.1.zip , 

![image](https://user-images.githubusercontent.com/3831847/140442561-b50d7b70-300f-4991-9de0-37b40fc2cf4f.png)

When I extract this zip file on Windows 10, with 7zip software, it complains:

![image](https://user-images.githubusercontent.com/3831847/140442540-cf928124-7bd7-4005-8dad-c960a6f32490.png)

**Comment by weiweiwei256** [comment]
这个 zip实际上是mac下的压缩包   我之后发布的版本会改下名字 避免误会   测试了下  应该不影响功能。所以应该会晚些处理。

**Comment by weiweiwei256** [comment]
v1.2.1 package and os in name.  Please download suitable verision.
