### ISSUE TITLE
MegSpot core dump

### ISSUE THREAD

**Issue by YAMLONG** [MegEngine/MegSpot#7]
Hi, downloaded the MegSpot-1.1.1.AppImage file from https://github.com/MegEngine/MegSpot/releases/download/v1.1.1/MegSpot-1.1.1.AppImage. When I launch this program on Linux (CentOS 7.3), it crashed and give me the following error:
![test00](https://user-images.githubusercontent.com/29030872/140858542-d58a0280-46c6-4069-ba8e-d109b3bfdfaa.png)

**Comment by YAMLONG** [comment]
Thanks for your reply.
The 'sysctl -w kernel.unprivileged_userns_clone=1' command is only valid for Ubuntu / Debian systems. If it is executed on CentOS systems, an error will be reported.

When executing MegSpot, add the --no-sandbox parameter, which can be executed successfully.

**Comment by weiweiwei256** [comment]
Thanks for your issue solution.  I will and no-sandbox parameter in megspot start arguments by default in the next version.
