### ISSUE TITLE
[Feature Request] 能够支持 server 模式, 用浏览器远程访问 UI 吗?

### ISSUE THREAD

**Issue by DIYer22** [MegEngine/MegSpot#8]
比如在服务器上启动 server 模式, 通过 cli 输入图片路径, 再通过浏览器访问 UI 界面.

缘由: 
- 很多图片或者实验都是在服务器端的.
- 方便分享给他人. (不用强制他人安装 megspot)
- 在文档里面添加 在线体验 demo (陌生人在感受效果前先安装软件, 是个困难的事情)

**Comment by weiweiwei256** [comment]
如果是Megvii的用户，可以直接使用lovelive平台完成图片的对比。算是megspot的线上版。如果是社会上的普通用户，就没办法了。  另外 web版和megspot的定位不符合。线上的没有本地app的读取速度和访问权限。需要提供完整的一套数据存储云空间。无论是难度和资源都是很大的问题。   
分享也类似，需要公网云服务器。
so,  现在没有考虑支持web端
