### ISSUE TITLE
可以加一个保存工程吗？

### ISSUE THREAD

**Issue by CXido** [MegEngine/MegSpot#9]
类似PSD一样，这样子如果发给其他人或者换电脑的时候更加方便
![1](https://user-images.githubusercontent.com/55381745/150682925-c84c66f0-4362-42bf-84f5-4ed743716778.jpg)

**Comment by weiweiwei256** [comment]
年后考虑实现，涉及的功能细节还是挺多的。

**Comment by hjwforever** [comment]
新版本v1.4.0已支持~
